# ref: https://github.com/NTBBloodbath/nvim/blob/38c58ea0684f6868bd3afe1528642cbb33eb0bd4/rocks.toml#L4
# rocks-config
[config]
auto_setup = true
colorscheme = "kanagawa-wave"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.0.0"
"rocks-dev.nvim" = "1.2.3"
"rocks-treesitter.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
"oil.nvim" = "2.10.0"
"neoscroll.nvim" = "0.2.0"
"nightfox.nvim" = "3.9.3"
"todo-comments.nvim" = "1.2.0"

[plugins."accelerated-jk.nvim"]
git = "github:rainbowhxch/accelerated-jk.nvim"
opt = true

# colorschemes
[plugins."kanagawa.nvim"]
version = "scm"
opt = true
colorscheme = [
  "kanagawa",
  "kanagawa-wave",
]

[plugins."github-nvim-theme"]
version = "1.0.2"
opt = true
