# ref: https://github.com/NTBBloodbath/nvim/blob/38c58ea0684f6868bd3afe1528642cbb33eb0bd4/rocks.toml#L4
# rocks-config
[config]
auto_setup = true
colorscheme = "kanagawa-wave"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
# NOTE: nvim-neorocks officials
"rocks.nvim" = "2.31.3"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.0.0"
"rocks-dev.nvim" = "1.2.3"
"rocks-treesitter.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
# NOTE: zero-config plugins
"dressing.nvim" = "2.2.2"

[plugins."kanagawa.nvim"]
version = "scm"
colorscheme = [
  "kanagawa",
  "kanagawa-dragon",
  "kanagawa-lotus",
  "kanagawa-wave",
]

[plugins."auto-save.nvim"]
version = "scm"
cmd = "ASToggle"
opt = true

[plugins."accelerated-jk.nvim"]
git = "github:rainbowhxch/accelerated-jk.nvim"
event = "BufRead"
keys = [
  {lhs = "j", rhs = "<Plug>(accelerated_jk_gj)", mode = "n", desc = "fast j" },
  {lhs = "k", rhs = "<Plug>(accelerated_jk_gk)", mode = "n", desc = "fast k" },
]
opt = true

[plugins."calendar-vim"]
git = "github:mattn/calendar-vim"
cmd = "Calendar"
opt = true

[plugins."vimdoc-ja"]
git = "github:vim-jp/vimdoc-ja"
# TODO: Fix it
#keys = [
#  { lhs = "h", mode = "c", desc = "open [H]elp" },
#]
#opt = true

[plugins."vim-ambiwidth"]
git = "github:rbtnn/vim-ambiwidth"
#opt = true

[plugins."vim-just"]
git = "github:NoahTheDuke/vim-just"
ft = "just"
opt = true

[plugins."vim-kitty"]
git = "github:fladson/vim-kitty"
ft = "kitty"
opt = true

[plugins."vim-quickrun"]
git = "github:thinca/vim-quickrun"
cmd = "QuickRun"
opt = true

[plugins."ron.vim"]
git = "github:ron-rs/ron.vim"
ft = "ron"
opt = true

[plugins."kdl.vim"]
git = "github:imsnif/kdl.vim"
ft = "kdl"
opt = true

[plugins."chezmoi.vim"]
git = "github:alker0/chezmoi.vim"
# this plugin DO NOT lazy loading
# see: https://github.com/alker0/chezmoi.vim#install
#opt = true

[plugins."align.nvim"]
git = "github:Vonr/align.nvim"
event = "BufRead"
opt = true

[plugins."transparent.nvim"]
git = "github:xiyaowong/transparent.nvim"
cmd = [
    "TransparentEnable",
    "TransparentDisable",
    "TransparentToggle",
]
opt = true

[plugins."satellite.nvim"]
git = "github:lewis6991/satellite.nvim"
