# ref: https://github.com/NTBBloodbath/nvim/blob/38c58ea0684f6868bd3afe1528642cbb33eb0bd4/rocks.toml#L4
# rocks-config
[config]
auto_setup = true
colorscheme = "kanagawa-wave"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
# NOTE: nvim-neorocks officials
"rocks.nvim" = "2.31.3"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.0.0"
"rocks-dev.nvim" = "1.2.3"
"rocks-treesitter.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
#"rocks-edit.nvim" = "scm"
# NOTE: zero-config plugins
"dressing.nvim" = "2.2.2"
"neoscroll.nvim" = "0.2.0"
# NOTE: tree-sitter parsers
tree-sitter-bash = "scm"
tree-sitter-c = "scm"
tree-sitter-c_sharp = "scm"
tree-sitter-cmake = "scm"
tree-sitter-cpp = "scm"
tree-sitter-css = "scm"
tree-sitter-djot = "scm"
tree-sitter-dockerfile = "scm"
tree-sitter-fish = "scm"
tree-sitter-git_config = "scm"
tree-sitter-git_rebase = "scm"
tree-sitter-gitattributes = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-go = "scm"
tree-sitter-gomod = "scm"
tree-sitter-gosum = "scm"
tree-sitter-gowork = "scm"
tree-sitter-graphql = "scm"
tree-sitter-html = "scm"
tree-sitter-ini = "scm"
tree-sitter-java = "scm"
tree-sitter-javascript = "scm"
tree-sitter-jq = "scm"
tree-sitter-jsdoc = "scm"
tree-sitter-json = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-json5 = "scm"
tree-sitter-kdl = "scm"
tree-sitter-latex = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-luap = "scm"
tree-sitter-luau = "scm"
tree-sitter-make = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-ninja = "scm"
tree-sitter-nix = "scm"
tree-sitter-python = "scm"
tree-sitter-regex = "scm"
tree-sitter-rst = "scm"
tree-sitter-ruby = "scm"
tree-sitter-rust = "scm"
tree-sitter-scala = "scm"
tree-sitter-scss = "scm"
tree-sitter-sql = "scm"
tree-sitter-svelte = "scm"
tree-sitter-swift = "scm"
tree-sitter-tsx = "scm"
tree-sitter-toml = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-vue = "scm"
tree-sitter-yaml = "scm"
tree-sitter-zig = "scm"
tree-sitter-just = "scm"
## NOTE: Linux or WSL only
#tree-sitter-ocaml = "scm"
#tree-sitter-ocaml_interface = "scm"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[treesitter.parser_map]
# Determine the filetype with ':lua =vim.bo[0].filetype'.
# NOTE: You don't actually have to add these examples.
# They are added by default.
#PKGBUILD = "bash"
#cls = "latex"
#sty = "latex"

[plugins."auto-save.nvim"]
version = "scm"
cmd = "ASToggle"
opt = true

[plugins."accelerated-jk.nvim"]
git = "github:rainbowhxch/accelerated-jk.nvim"
event = "BufRead"
keys = [
  {lhs = "j", rhs = "<Plug>(accelerated_jk_gj)", mode = "n", desc = "fast j" },
  {lhs = "k", rhs = "<Plug>(accelerated_jk_gk)", mode = "n", desc = "fast k" },
]
opt = true

[plugins."calendar-vim"]
git = "github:mattn/calendar-vim"
cmd = "Calendar"
opt = true

[plugins."vimdoc-ja"]
git = "github:vim-jp/vimdoc-ja"
# TODO: Fix it
#keys = [
#  { lhs = "h", mode = "c", desc = "open [H]elp" },
#]
#opt = true

[plugins."vim-ambiwidth"]
git = "github:rbtnn/vim-ambiwidth"
#opt = true

[plugins."vim-just"]
git = "github:NoahTheDuke/vim-just"
ft = "just"
opt = true

[plugins."vim-kitty"]
git = "github:fladson/vim-kitty"
ft = "kitty"
opt = true

[plugins."vim-quickrun"]
git = "github:thinca/vim-quickrun"
cmd = "QuickRun"
opt = true

[plugins."ron.vim"]
git = "github:ron-rs/ron.vim"
ft = "ron"
opt = true

[plugins."kdl.vim"]
git = "github:imsnif/kdl.vim"
ft = "kdl"
opt = true

[plugins."chezmoi.vim"]
git = "github:alker0/chezmoi.vim"
# this plugin DO NOT lazy loading
# see: https://github.com/alker0/chezmoi.vim#install
#opt = true

[plugins."align.nvim"]
git = "github:Vonr/align.nvim"
event = "BufRead"
opt = true

[plugins."transparent.nvim"]
git = "github:xiyaowong/transparent.nvim"
cmd = [
    "TransparentEnable",
    "TransparentDisable",
    "TransparentToggle",
]
opt = true

[plugins."satellite.nvim"]
git = "github:lewis6991/satellite.nvim"
#opt = true

# NOTE: cond = false now
#[plugins."modeline.nvim"]
#git = "github:nvimdev/modeline.nvim"
#event = ["BufReadPre", "BufNewFile"]
#opt = true

[plugins."modes.nvim"]
git = "github:mvllow/modes.nvim"
tag = "v0.2.0"
event = "BufRead"
opt = true

[plugins."no-neck-pain.nvim"]
version = "1.14.1"
cmd = [
    "NoNeckPain",
    "NoNeckPainResize",
    "NoNeckPainToggleLeftSide",
    "NoNeckPainToggleRightSide",
    "NoNeckPainWidthUp",
    "NoNeckPainWidthDown",
]
opt = true

[plugins.nvim-autopairs]
version = "scm"
event = "InsertEnter"
opt = true

[plugins.nvim-cursorline]
version = "scm"
opt = true

[plugins.nvim-hlslens]
git = "github:kevinhwang91/nvim-hlslens"
keys = [
  {lhs = "<leader>l", desc ="run `:nohlsearch` and export results to quickfix"},
]
#opt = true

[plugins.nvim-insx]
git = "github:hrsh7th/nvim-insx"
#opt = true

[plugins."overseer.nvim"]
version = "1.4.0"
cmd = [
    "OverseerOpen",
    "OverseerClose",
    "OverseerToggle",
    "OverseerSaveBundle",
    "OverseerLoadBundle",
    "OverseerDeleteBundle",
    "OverseerRunCmd",
    "OverseerRun",
    "OverseerInfo",
    "OverseerBuild",
    "OverseerQuickAction",
    "OverseerTaskAction",
    "OverseerClearCache",
]
opt = true

[plugins."pantran.nvim"]
version = "scm"
keys = [
{ lhs = "tr", desc = "Run Translate" },
{ lhs = "trr", desc = "Run Translate" },
]
cmd = "Pantran"
opt = true

[plugins."persistence.nvim"]
version = "2.0.0"
event = "BufReadPre"
opt = true

[plugins."15puzzle.nvim"]
version = "1.4.1"
cmd = "Play15puzzle"
opt = true

[plugins."screenkey.nvim"]
version = "2.1.0"
cmd = "Screenkey"
opt = true

# NOTE: cond = false now
#[plugins."staline.nvim"]
#version = "scm"
#event = [ "BufReadPre", "BufNewFile" ]
#opt = true

[plugins."ts-comments.nvim"]
version = "1.2.0"
event = "DeferredUIEnter"
opt = true

[plugins."which-key.nvim"]
version = "2.1.0"
event = "DeferredUIEnter"
opt = true

# NOTE: cond = false now
#[plugins."windline.nvim"]
#version = "1.1.0"
#event = [ "BufReadPre", "BufNewFile"]
#opt = true

[plugins."zen-mode.nvim"]
version = "1.3.0"
cmd = "ZenMode"
opt = true

[plugins."nvim-markdown"]
git = "github:ixru/nvim-markdown"
ft = "markdown"
opt = true

[plugins."pandoc.nvim"]
git = "github:aspeddro/pandoc.nvim"
opt = true

[plugins."scope.nvim"]
git = "github:tiagovla/scope.nvim"
cmd = "ScopeMoveBuf"
opt = true

[plugins."sidebar.nvim"]
git = "github:sidebar-nvim/sidebar.nvim"
cmd = [
    "SidebarNvimToggle",
    "SidebarNvimClose",
    "SidebarNvimOpen",
    "SidebarNvimUpdate",
    "SidebarNvimResize",
    "SidebarNvimFocus",
]
opt = true

[plugins."strat-hero.nvim"]
git = "github:willothy/strat-hero.nvim"
cmd = "StratHero"
opt = true

[plugins."template.nvim"]
git = "github:nvimdev/template.nvim"
cmd = "Template"
#opt = true

[plugins."typos.nvim"]
git = "github:poljar/typos.nvim"
event = "BufRead"
opt = true

[plugins."wezterm.nvim"]
git = "github:mimikun/wezterm.nvim"
dir = "~/ghq/github.com/mimikun/dev-plugins/wezterm.nvim"

[plugins.alpha-nvim]
version = "scm"
event = "VimEnter"
opt = true

[plugins."bufferline.nvim"]
version = "4.6.1"
#dependencies = { "nvim-tree/nvim-web-devicons" },
event = ["BufReadPre", "BufNewFile"]
cmd = [
    "BufferLineTabRename",
    "BufferLineGroupClose",
    "BufferLineGroupToggle",
    "BufferLineTogglePin",
    "BufferLineSortByExtension",
    "BufferLineSortByDirectory",
    "BufferLineSortByTabs",
    "BufferLineCycleNext",
    "BufferLineCyclePrev",
    "BufferLineCloseRight",
    "BufferLineCloseLeft",
    "BufferLineCloseOthers",
    "BufferLinePick",
    "BufferLineGoToBuffer",
    "BufferLineMoveNext",
    "BufferLineMovePrev",
]
opt = true

[plugins."oil.nvim"]
version = "2.10.0"
cmd = "Oil"
opt = true

## TODO:
#[plugins."oil-git-status.nvim"]
#git = "github:refractalize/oil-git-status.nvim"
##opt = true
#
#[bundles.oil]
#items = [
#"oil.nvim",
#"oil-git-status.nvim",
#]

## NOTE: cond = false now
#[plugins.dashboard-nvim]
#version = "scm"
#cmd = [
#    "Dashboard",
#    "DbProjectDelete",
#    "DashboardUpdateFooter",
#]
#event = "VimEnter"
##opt = true
##dependencies = { "nvim-tree/nvim-web-devicons" },

## NOTE: cond = false now
#[plugins."dial.nvim"]
#version = "0.4.0"
#event = "VimEnter"
#keys = [
#    { lhs = "<C-a>", desc = "<C-a> increment" },
#    { lhs = "<C-x>", desc = "<C-x> decrement" },
#]
#opt = true

[plugins."feline.nvim"]
version = "1.6.2"
event = [ "BufReadPre", "BufNewFile" ]
opt = true

[plugins."smoothcursor.nvim"]
version = "scm"
event = "BufRead"
opt = true

## NOTE: cond = false now
#[plugins."flash.nvim"]
#version = "1.18.3"
#event = "DeferredUIEnter"
#keys = [
#    { lhs = "s", desc = "Flash" },
#    { lhs = "S", desc = "Flash Treesitter" },
#    { lhs = "r", desc = "Remote Flash" },
#    { lhs = "R", desc = "Treesitter Search" },
#    { lhs = "<c-s>", desc = "Toggle Flash Search" },
#    { lhs = "<leader>h", desc = "Flash HopWord" },
#]
#opt = true


[plugins."headlines.nvim"]
version = "scm"
opt = true

## NOTE: cond = false now
#[plugins."heirline.nvim"]
#version = "1.0.6"
#event = "UIEnter"
#opt = true

[plugins."hover.nvim"] 
version = "scm"
keys = [
    { lhs = "K", desc = "hover.nvim" },
    { lhs = "gK", desc = "hover.nvim (select)" },
    { lhs = "<C-p>", desc = "hover.nvim (previous source)" },
    { lhs = "<C-n>", desc = "hover.nvim (next source)" },
    { lhs = "<MouseMove>", desc = "hover.nvim (mouse)" },
]
opt = true

## NOTE: cond = false now
#[plugins."incline.nvim"]
#version = "0.0.1"
#event = "DeferredUIEnter"
#opt = true

[plugins."indent-blankline.nvim"]
version = "3.7.1"
cmd = [
    "IBLEnable",
    "IBLDisable",
    "IBLToggle",
    "IBLEnableScope",
    "IBLDisableScope",
    "IBLToggleScope",
]
event = "VimEnter"
#opt = true

[plugins."lazygit.nvim"]
version = "scm"
cmd = [
    "LazyGit",
    "LazyGitConfig",
    "LazyGitCurrentFile",
    "LazyGitFilter",
    "LazyGitFilterCurrentFile",
]
opt = true

[plugins."lualine.nvim"]
version = "scm"
event = [ "BufReadPre", "BufNewFile" ]
opt = true

## NOTE: cond = false now
#[plugins.nvim-scrollbar]
#version = "scm"
#event = "VimEnter"
##opt = true

[plugins."sqlite.lua"]
version = "1.2.2"
opt = true

[plugins."trouble.nvim"]
version = "3.4.3"
cmds = [
    "Trouble",
    "TroubleClose",
    "TroubleToggle",
    "TroubleRefresh",
]
opt = true

[plugins."dmacro.nvim"]
git = "github:tani/dmacro.nvim"
keys = [
    { lhs = "<C-t>", desc = "Use dmacro" },
]
opt = true

## WARN: deprecated error
#[plugins."ccc.nvim"]
#git = "github:uga-rosa/ccc.nvim"
##version = "1.6.0"
#event = "BufRead"
#opt = true

[plugins."codeshot.nvim"]
git = "github:SergioRibera/codeshot.nvim"
opt = true

[plugins."comment.nvim"]
version = "0.8.0"
#git = "github:numToStr/Comment.nvim"
event = "BufRead"
opt = true

[plugins."dotfyle-metadata.nvim"]
git = "github:creativenull/dotfyle-metadata.nvim"
cmd = [
    "DotfyleGenerate",
    "DotfyleOpen",
]
opt = true

[plugins."git.nvim"]
git = "github:dinhhuy258/git.nvim"
cmd = [
    "Git",
    "GitBlame",
    "GitDiff",
    "GitDiffClose",
    "GitCreatePullRequest",
    "GitCreatePullRequest",
    "GitRevert",
    "GitRevertFile",
]
opt = true

[plugins."glow.nvim"]
version = "0.2.0"
#git = "github:ellisonleao/glow.nvim"
cmd = "Glow"
opt = true

[plugins."2048.nvim"]
version = "2.8.2"
#git = "github:NStefan002/2048.nvim"
cmd = "Play2048"
opt = true

[plugins."image_preview.nvim"]
git = "github:adelarsq/image_preview.nvim"
event = "DeferredUIEnter"
opt = true

[plugins."marks.nvim"]
version = "scm"
#git = "github:chentoast/marks.nvim"
cmd = [
    "MarksToggleSigns",
    "MarksListBuf",
    "MarksListGlobal",
    "MarksListAll",
    "BookmarksList group_number",
    "BookmarksListAll",
    "MarksQFListBuf",
    "MarksQFListGlobal",
    "MarksQFListAll",
    "BookmarksQFList group_number",
    "BookmarksQFListAll",
]
opt = true

## NOTE: cond = false now
#[plugins."drop.nvim"]
#git = "github:folke/drop.nvim"
#event = "VimEnter"
#opt = true

[plugins."flagmode.nvim"]
git = "github:prichrd/flagmode.nvim"
cmd = [
    "FlagToggle",
    "FlagActivate",
    "FlagDeactivate",
]
opt = true

[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"
event = "VimEnter"
keys = [
    { lhs = "g[", desc = "Jump to the previous hunk in the current buffer." },
    { lhs = "g]", desc = "Jump to the next hunk in the current buffer." },
    { lhs = "gh", desc = "Toggle diff highlights" },
    { lhs = "gp", desc = "Preview the hunk at the cursor position inline in the buffer." },
]
opt = true

[plugins."hop.nvim"]
git = "github:smoka7/hop.nvim"
keys = [
    { lhs = "<leader>h", desc = "HopWord" },
]
cmd = [
    "HopWord",
    "HopChar1",
    "HopChar2",
    "HopPattern",
    "HopLine",
    "HopLineStart",
    "HopAnywhere",
    "HopNodes",
    "HopYankChar1",
]
opt = true

# NOTE: cond = false now
#[plugins."huez.nvim"]
#git = "github:vague2k/huez.nvim"
#event = "UIEnter"
#cmd = [
#    "Huez",
#    "HuezEnsured",
#    "HuezLive",
#    "HuezFavorites",
#]
#opt = true

[plugins."human-rights.nvim"]
git = "github:mimikun/human-rights.nvim"
cmd = [
    "ShowCpu",
    "ShowMemory",
    "ShowParallelism",
    "ShowDisk",
]
opt = true

# colorschemes
[plugins."kanagawa.nvim"]
version = "scm"
colorscheme = [
  "kanagawa",
  "kanagawa-dragon",
  "kanagawa-lotus",
  "kanagawa-wave",
]
opt = true

## Can't use now
#[plugins.catppuccin]
#version = "0.1.0"
#colorscheme = [
#        "catppuccin",
#        "catppuccin-latte",
#        "catppuccin-frappe",
#        "catppuccin-macchiato",
#        "catppuccin-mocha",
#]
#opt = true

[plugins.github-nvim-theme]
version = "1.0.2"
colorscheme = [
"github_dark",
"github_dark_colorblind",
"github_dark_default",
"github_dark_dimmed",
"github_dark_high_contrast",
"github_dark_tritanopia",
"github_light",
"github_light_colorblind",
"github_light_default",
"github_light_high_contrast",
"github_light_tritanopia",
"github_dimmed",
]
opt = true

[plugins."material.nvim"]
version = "scm"
colorscheme = [
"material",
"material-darker",
"material-lighter",
"material-oceanic",
"material-palenight",
"material-deep-ocean",
]
opt = true

[plugins."monokai.nvim"]
version = "scm"
colorscheme = [
"monokai",
"monokai_pro",
"monokai_ristretto",
"monokai_soda",
]
opt = true

[plugins."tokyonight.nvim"]
version = "4.3.0"
colorscheme = [
"tokyonight",
"tokyonight-day",
"tokyonight-moon",
"tokyonight-night",
"tokyonight-storm",
]
opt = true

[plugins.witch]
git = "github:sontungexpt/witch"
colorscheme = [
"witch-dark",
"witch-light",
]
opt = true

[plugins."nightfox.nvim"]
version = "3.9.3"
opt = true

[plugins."sweetie.nvim"]
version = "3.1.1"
opt = true

[plugins."ariake.nvim"]
git = "github:jim-at-jibba/ariake.nvim"
colorscheme = "ariake"
opt = true

[plugins."/Abstract-cs"]
git = "github:Abstract-IDE/Abstract-cs"
colorscheme = "abscs"
opt = true

[plugins."yash.nvim"]
git = "github:kihachi2000/yash.nvim"
colorscheme = "yash"
opt = true

[plugins."kurayami.nvim"]
git = "github:kevinm6/kurayami.nvim"
colorscheme = "kurayami"
opt = true

[plugins."vim-dogrun"]
git = "github:wadackel/vim-dogrun"
colorscheme = "dogrun"
opt = true

[plugins.momiji]
git = "github:kyoh86/momiji"
colorscheme = "momiji"
opt = true

[plugins."kanagawa-paper.nvim"]
git = "github:sho-87/kanagawa-paper.nvim"
colorscheme = "kanagawa-paper"
opt = true

[plugins."fluoromachine.nvim"]
git = "github:maxmx03/fluoromachine.nvim"
colorscheme = "fluoromachine"
opt = true

[plugins."everblush"]
git = "github:Everblush/nvim"
colorscheme = "everblush"
opt = true

[plugins.evergarden]
git = "github:comfysage/evergarden"
colorscheme = "evergarden"
opt = true

[plugins."eldritch.nvim"]
git = "github:eldritch-theme/eldritch.nvim"
colorscheme = "eldritch"
opt = true

[plugins."dark_flat.nvim"]
git = "github:sekke276/dark_flat.nvim"
colorscheme = "dark_flat"
opt = true

[plugins.edge]
git = "github:sainnhe/edge"
colorscheme = "edge"
opt = true

[plugins.sonokai]
git = "github:sainnhe/sonokai"
colorscheme = "sonokai"
opt = true

[plugins."kyotonight.vim"]
git = "github:shrikecode/kyotonight.vim"
colorscheme = "kyotonight"
opt = true

[plugins.neon]
git = "github:rafamadriz/neon"
colorscheme = "neon"
opt = true

[plugins."tokyodark.nvim"]
git = "github:tiagovla/tokyodark.nvim"
colorscheme = "tokyodark"
opt = true

[plugins."nord.nvim"]
git = "github:shaunsingh/nord.nvim"
colorscheme = "nord"
opt = true

[plugins."oldworld.nvim"]
git = "dgox16/oldworld.nvim"
colorscheme = "oldworld"
opt = true

[plugins."penumbra.nvim"]
git = "github:Allianaab2m/penumbra.nvim"
colorscheme = "penumbra"
opt = true

[plugins."cyberdream.nvim"]
git = "github:scottmckendry/cyberdream.nvim"
colorscheme = "cyberdream"
opt = true

[plugins."mellow.nvim"]
git = "github:mellow-theme/mellow.nvim"
colorscheme = "mellow"
opt = true

#--- nightfall_themes
#colorscheme = [
#"nightfall",
#"deeper-night",
#"maron",
#]

#--- monokai_pro_themes
#colorscheme = [
#"monokai-pro",
#"monokai-pro-classic",
#"monokai-pro-default",
#"monokai-pro-machine",
#"monokai-pro-octagon",
#"monokai-pro-ristretto",
#"monokai-pro-spectrum",
#]

#--- pastelnight_themes
#colorscheme = [
#"pastelnight",
#"pastelnight-highcontrast",
#]

#--- lackluster_themes
#colorscheme = [
#"lackluster",
#"lackluster-dark",
#"lackluster-hack",
#"lackluster-mint",
#"lackluster-night",
#]
