"b0o/lavi.nvim"
dependencies = { "rktjmp/lush.nvim" }
colorscheme = "lavi"

"loganswartz/sunburn.nvim"
colorscheme = "sunburn"
dependencies = { "loganswartz/polychrome.nvim" }

"m15a/nvim-srcerite"
colorscheme = "srcerite"
dependencies = { "Iron-E/nvim-highlite" }
init = function()
    vim.g.srcerite_inverse_visual = true
    vim.g.srcerite_inverse_search = false
    vim.g.srcerite_inverse_match_paren = false
end
