#"sontungexpt/witch"

#"pauchiner/pastelnight.nvim"
#local opts = {
#    transparent = vim.g.transparent_enabled,
#}

#"loctvl842/monokai-pro.nvim"
#local opts = {
#    transparent_background = vim.g.transparent_enabled,
#}

#"slugbyte/lackluster.nvim"
#local lackluster = require("lackluster")
#
#lackluster.setup({
#    tweak_syntax = {
#        comment = lackluster.color.gray4,
#        --comment = lackluster.color.gray5,
#    },
#    tweak_background = {
#        normal = "none",
#        telescope = "none",
#        menu = lackluster.color.gray3,
#        popup = "default",
#    },
#})

"rafamadriz/neon"
colorscheme = "neon"
config = function()
    vim.g.neon_style = "default"
    --vim.g.neon_style = "dark"
    --vim.g.neon_style = "light"
    vim.g.neon_italic_comment = false
    vim.g.neon_italic_keyword = false
    vim.g.neon_italic_boolean = false
    vim.g.neon_italic_function = false
    vim.g.neon_italic_variable = false
    vim.g.neon_bold = false
    vim.g.neon_transparent = vim.g.transparent_enabled
end

"b0o/lavi.nvim"
dependencies = { "rktjmp/lush.nvim" }
colorscheme = "lavi"

"loganswartz/sunburn.nvim"
colorscheme = "sunburn"
dependencies = { "loganswartz/polychrome.nvim" }

"m15a/nvim-srcerite"
colorscheme = "srcerite"
dependencies = { "Iron-E/nvim-highlite" }
init = function()
    vim.g.srcerite_inverse_visual = true
    vim.g.srcerite_inverse_search = false
    vim.g.srcerite_inverse_match_paren = false
end

"tiagovla/tokyodark.nvim"
colorscheme = "tokyodark"
local opts = {
transparent_background = vim.g.transparent_enabled,
}

"shaunsingh/nord.nvim"
colorscheme = "nord"
config = function()
    vim.g.nord_disable_background = vim.g.transparent_enabled
end

"dgox16/oldworld.nvim"
colorscheme = "oldworld"
local opts = {
-- enable terminal colors
terminal_colors = true,
-- You can pass the style using the format: style = true
styles = {
    -- style for comments
    comments = { italic = true },
    -- style for keywords
    keywords = {},
    -- style for identifiers
    identifiers = {},
    -- style for functions
    functions = { italic = true },
    -- style for variables
    variables = {},
    -- style for booleans
    booleans = {},
},
-- You can disable/enable integrations
integrations = {
    alpha = true,
    cmp = true,
    flash = true,
    gitsigns = true,
    hop = false,
    indent_blankline = true,
    lazy = true,
    lsp = true,
    markdown = true,
    mason = true,
    navic = false,
    neo_tree = false,
    noice = true,
    notify = true,
    rainbow_delimiters = true,
    telescope = true,
    treesitter = true,
},
}

"Allianaab2m/penumbra.nvim"
colorscheme = "penumbra"
local opts = {
italic_comment = false,
transparent_bg = vim.g.transparent_enabled,
show_end_of_buffer = false,
light = false,
contrast = nil,
--contrast = "plus",
--contrast = "plusplus",
}

"scottmckendry/cyberdream.nvim"
colorscheme = "cyberdream"
local opts = {
transparent = vim.g.transparent_enabled,
italic_comments = true,
hide_fillchars = true,
borderless_telescope = true,
terminal_colors = true,
}

"mellow-theme/mellow.nvim"
colorscheme = "mellow"
init = function()
    vim.g.mellow_italic_comments = true
    vim.g.mellow_italic_keywords = false
    vim.g.mellow_italic_booleans = false
    vim.g.mellow_italic_functions = false
    vim.g.mellow_italic_variables = false
    vim.g.mellow_bold_comments = false
    vim.g.mellow_bold_keywords = false
    vim.g.mellow_bold_booleans = false
    vim.g.mellow_bold_functions = false
    vim.g.mellow_bold_variables = false
    vim.g.mellow_transparent = vim.g.transparent_enabled
end
