--- witch_themes
colorscheme = [
"witch-dark",
"witch-light",
]
--- nightfall_themes
colorscheme = [
"nightfall",
"deeper-night",
"maron",
]
--- tokyonight_themes
colorscheme = [
"tokyonight",
"tokyonight-day",
"tokyonight-moon",
"tokyonight-night",
"tokyonight-storm",
]
--- monokai_themes
colorscheme = [
"monokai",
"monokai_pro",
"monokai_ristretto",
"monokai_soda",
]
--- monokai_pro_themes
colorscheme = [
"monokai-pro",
"monokai-pro-classic",
"monokai-pro-default",
"monokai-pro-machine",
"monokai-pro-octagon",
"monokai-pro-ristretto",
"monokai-pro-spectrum",
]
--- pastelnight_themes
colorscheme = [
"pastelnight",
"pastelnight-highcontrast",
]
--- lackluster_themes
colorscheme = [
"lackluster",
"lackluster-dark",
"lackluster-hack",
"lackluster-mint",
"lackluster-night",
]
--- lua_other_themes
{
    name = "neon",
    colorscheme = "neon",
},
{
    name = "sweetie",
    colorscheme = "sweetie",
},
{
    name = "lavi",
    colorscheme = "lavi",
},
{
    name = "sunburn",
    colorscheme = "sunburn",
},
{
    name = "srcerite",
    colorscheme = "srcerite",
},
{
    name = "tokyodark",
    colorscheme = "tokyodark",
},
{
    name = "nord",
    colorscheme = "nord",
},
{
    name = "oldworld",
    colorscheme = "oldworld",
},
{
    name = "penumbra",
    colorscheme = "penumbra",
},
{
    name = "cyberdream",
    colorscheme = "cyberdream",
},
{
    name = "mellow",
    colorscheme = "mellow",
},
{
    name = "yash",
    colorscheme = "yash",
},
{
    name = "nightfox",
    colorscheme = "nightfox",
},
{
    name = "kanagawa-paper",
    colorscheme = "kanagawa-paper",
},
{
    name = "eldritch",
    colorscheme = "eldritch",
},
{
    name = "ariake",
    colorscheme = "ariake",
},
{
    name = "abstract",
    colorscheme = "abscs",
},
{
    name = "evergarden",
    colorscheme = "evergarden",
},
{
    name = "dark_flat",
    colorscheme = "dark_flat",
},
{
    name = "everblush",
    colorscheme = "everblush",
},
{
    name = "kurayami",
    colorscheme = "kurayami",
},
{
    name = "fluoromachine",
    colorscheme = "fluoromachine",
},
{
    name = "sonokai",
    colorscheme = "sonokai",
},
{
    name = "kyotonight",
    colorscheme = "kyotonight",
},
{
    name = "momiji",
    colorscheme = "momiji",
},
{
    name = "edge",
    colorscheme = "edge",
},
{
    name = "dogrun",
    colorscheme = "dogrun",
},
{
    name = "gaming",
    colorscheme = "gaming",
},
