#"pauchiner/pastelnight.nvim"
#local opts = {
#    transparent = vim.g.transparent_enabled,
#}

#"loctvl842/monokai-pro.nvim"
#local opts = {
#    transparent_background = vim.g.transparent_enabled,
#}

#"slugbyte/lackluster.nvim"
#local lackluster = require("lackluster")
#
#lackluster.setup({
#    tweak_syntax = {
#        comment = lackluster.color.gray4,
#        --comment = lackluster.color.gray5,
#    },
#    tweak_background = {
#        normal = "none",
#        telescope = "none",
#        menu = lackluster.color.gray3,
#        popup = "default",
#    },
#})
