#    "nvim-telescope/telescope-frecency.nvim",
#    "danielfalk/smart-open.nvim",
#    "ghassan0/telescope-glyph.nvim",
#    "xiyaowong/telescope-emoji.nvim",
#    "fdschmidt93/telescope-egrepify.nvim",
#    "nvim-telescope/telescope-file-browser.nvim",
#    "vuki656/package-info.nvim",
#    "tiagovla/scope.nvim",
#    "nvim-lua/popup.nvim",
#    "jvgrootveld/telescope-zoxide",
#    "debugloop/telescope-undo.nvim",
#    "epwalsh/pomo.nvim",
#    NOTE: Add fzf_sorter if not a Windows
#    Very difficult to build fzf on Windows
#    if not is_windows then
#    { "nvim-telescope/telescope-fzf-native.nvim", build = "make" }
#    "dharmx/telescope-media.nvim",
