[plugins."ccc.nvim"]
git = "github:uga-rosa/ccc.nvim"
event = "BufRead",
opt = true

# lua/plugins/ccc-nvim.lua
require("ccc").setup({
        highlighter = {
            auto_enable = true,
            lsp = true,
        },
})

#--------------------------------------------------------------------------------------

[plugins."codeshot.nvim"]
git = "github:SergioRibera/codeshot.nvim"
opt = true

#--------------------------------------------------------------------------------------

[plugins."Comment.nvim"]
git = "github:numToStr/Comment.nvim"
event = "BufRead"
opt = true

#--------------------------------------------------------------------------------------

[plugins."dotfyle-metadata.nvim"]
git = "github:creativenull/dotfyle-metadata.nvim"
cmd = [
    "DotfyleGenerate",
    "DotfyleOpen",
]
opt = true

#--------------------------------------------------------------------------------------

[plugins."git.nvim"]
git = "github:dinhhuy258/git.nvim"
cmd = [
    "Git",
    "GitBlame",
    "GitDiff",
    "GitDiffClose",
    "GitCreatePullRequest",
    "GitCreatePullRequest",
    "GitRevert",
    "GitRevertFile",
]
opt = true

#--------------------------------------------------------------------------------------

[plugins."glow.nvim"]
git = "github:ellisonleao/glow.nvim"
cmd = "Glow"
opt = true

#--------------------------------------------------------------------------------------

[plugins."2048.nvim"]
git = "github:NStefan002/2048.nvim"
cmd = "Play2048"
opt = true

#--------------------------------------------------------------------------------------

[plugins."image_preview.nvim"]
git = "github:adelarsq/image_preview.nvim"
event = "DeferredUIEnter"
opt = true

#--------------------------------------------------------------------------------------

[plugins."marks.nvim"]
git = "github:chentoast/marks.nvim"
cmd = [
    "MarksToggleSigns",
    "MarksListBuf",
    "MarksListGlobal",
    "MarksListAll",
    "BookmarksList group_number",
    "BookmarksListAll",
    "MarksQFListBuf",
    "MarksQFListGlobal",
    "MarksQFListAll",
    "BookmarksQFList group_number",
    "BookmarksQFListAll",
]
opt = true


# lua/plugins/marks-nvim.lua
require("marks").setup({
  builtin_marks = {
      "'",
      "^",
      ".",
      "<",
      ">",
  },
  default_mappings = true,
  signs = true,
  cyclic = true,
  force_write_shada = false,
  refresh_interval = 150,
  sign_priority = 10,
  excluded_filetypes = {},
  excluded_buftypes = {},
  mappings = {},
})

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------

# TODO:

#--------------------------------------------------------------------------------------

